### ISSUE TITLE
Breaks trying to write to a file rather than stdout

### ISSUE THREAD

**Issue by kergoth** [solvire/goodreads_api#1]
```
› gr user:books --user_id [my id] >books.xml
Traceback (most recent call last):
  File "/Users/kergoth/.local/bin/gr", line 9, in <module>
    load_entry_point('gr==0.1.0', 'console_scripts', 'gr')()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 522, in main
    _dispatch_cmd(method, args)
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 80, in _dispatch_cmd
    method(args)
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 307, in user_books
    print(r.text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 11344: ordinal not in range(128)
```

Tested on both osx and linux, both configured for en_US.UTF-8 across the board.

**Comment by solvire** [comment]
I'll take a look. I haven't messed with it in a while so maybe I changed something in the mean time.

**Comment by kergoth** [comment]
Not a problem, thanks. There are surprisingly few projects out there for interacting with the goodreads api from the commandline.

**Comment by solvire** [comment]
I'm kinda glad someone got some use out of it. 
Considering how big the audience on there is any author would be well inclined to growth hack that service. Before amazon locks it down.

**Comment by solvire** [comment]
Have you tried since my last commits? 
I haven't had a ton of time to work on it lately, but I think it was operational. 
Updated a bunch on docs and settings stuff.

**Comment by kergoth** [comment]
I haven't had a chance, but will take a look sometime soon. Thanks.

**Comment by kergoth** [comment]
Attempt to auth:authenticate:

```
Traceback (most recent call last):
  File "/Users/kergoth/.local/bin/gr", line 9, in <module>
    load_entry_point('gr==0.1.0', 'console_scripts', 'gr')()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 624, in main
    cli = GRClient()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 208, in __init__
    self.setup_config()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 214, in setup_config
    self.config.readfp(open(self.env_file))
IOError: [Errno 2] No such file or directory: '/Users/kergoth/.goodreads_api.ini'
```

After touching /Users/kergoth/.goodreads_api.ini:

```
Authenticating client
Getting OAuth
Traceback (most recent call last):
  File "/Users/kergoth/.local/bin/gr", line 9, in <module>
    load_entry_point('gr==0.1.0', 'console_scripts', 'gr')()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 644, in main
    _dispatch_cmd(method, args)
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 99, in _dispatch_cmd
    response = method(args)
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/gr.py", line 296, in auth_authenticate
    url = self.session.oauth_start()
  File "/Users/kergoth/.local/share/virtualenvs/goodreads_api/lib/python2.7/site-packages/client/session.py", line 40, in oauth_start
    goodreads_service.get_request_token(header_auth=True)
NameError: global name 'goodreads_service' is not defined
```

**Comment by solvire** [comment]
I'm pretty new to python but I am having trouble finding a good pattern or utility for maintaining sessions on the CLI. I'll have to go through and see what it's kicking back there.
